### ISSUE TITLE
Implement a simple searchform

### ISSUE THREAD

**Issue by Zillion01** [DirkPersky/rte-ckeditor-fontawesome#2]
Hi,

In the current state it's not very user friendly to find an icon.

Maybe implement a simple jQuery searchbox: while you type all other icons disappear which names do not contain the typed characters. Also while searching get rid of the categories.

Example code see function jpFaqSearchForm https://github.com/Zillion01/jpfaq/blob/master/Resources/Public/Javascript/jpFaq.js

grts

**Comment by DirkPersky** [comment]
Hi,

Is included to the new version.
